INSERT INTO TOURPLACE VALUES ( 1 , 'MYSORE' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 2 , 'OOTY' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 3 , 'PANALII' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 4 , 'TIRUCHI' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 5 , 'CHIDAMBARAM' , 'ALL SEASON' ) ;

INSERT INTO TOURPLACE VALUES ( 6 , 'GAYA' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 7 , 'NEPAL' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 8 , 'KASHI' , 'ALL SESAON' ) ;
INSERT INTO TOURPLACE VALUES ( 9 , 'TIGER HILLS' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 10 , 'AYODYA' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 11 , 'JAIPUR' , 'WINTER' ) ;
INSERT INTO TOURPLACE VALUES ( 12 , 'ALLAHABAD' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 13 , 'VARANASI','ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 14 , 'SARANATH' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 15 , 'KATTMANDU' ,'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 16 , 'POKHRA' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 17 , 'KOLKOTTA' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 18 , 'SUNOUIL' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 19 , 'PATNA' , 'ALL SESAON' ) ;
INSERT INTO TOURPLACE VALUES ( 20 , 'NALANDA' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 21 , 'JANAKAPURI' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 22 , 'DARJILING' , 'WINTER' ) ;
INSERT INTO TOURPLACE VALUES ( 23 , 'KONARK' , 'SUMMER' ) ;

INSERT INTO TOURPLACE VALUES ( 24 , 'HARIDWAR' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 25 , 'MUSSORIE' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 26 , 'DELHI' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 27 , 'AMER' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 28 , 'FHATEPUR SIKRI' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 29 , 'AGRA' , 'ALL SESAON' ) ;
INSERT INTO TOURPLACE VALUES ( 30 , 'MATHURA' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 31 , 'BRIDAVAN' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 32 , 'HRSHIKESH' , 'WINTER' ) ;
INSERT INTO TOURPLACE VALUES ( 33 , 'SHIMLA' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 34 , 'KUFRIR' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 35 , 'AMRITHSAR' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 36 , 'CHANDIGUD' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 37 , 'KURUKSHETRA' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 38 , 'PUSHKAR' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 39 , 'UADYPUR' , 'ALL SESAON' ) ;
INSERT INTO TOURPLACE VALUES ( 40 , 'MOUNT ABU' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 41 , 'JODHPUR' , 'ALL SEASON' ) ;

INSERT INTO TOURPLACE VALUES ( 42 , 'SHRIRANGAM' , 'WINTER' ) ;
INSERT INTO TOURPLACE VALUES ( 43 , 'TANJAVUR' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 44 , 'MANGALORE' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 45, 'UDUPI' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 46 , 'TRIVANDRUM' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 47 , 'MADHURAI' , 'ALL SESAON' ) ;
INSERT INTO TOURPLACE VALUES ( 48 , 'KOLLUR' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 49 , 'MURUDASHWARA' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 50 , 'GOKARNA' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 51 , 'MAHABALESHWAR' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 52 , 'PUNE' , 'WINTER' ) ;
INSERT INTO TOURPLACE VALUES ( 53 , 'KOLHAPUR' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 54 , 'TIRUPATHI' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 55, 'SRI KALAHASTHI' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 56 , 'AHOBALAM' , 'ALL SEASON' ) ;
INSERT INTO TOURPLACE VALUES ( 57 , 'MAHANANDI' , 'ALL SESAON' ) ;
INSERT INTO TOURPLACE VALUES (58 , 'SRISHYLAM' , 'SUMMER' ) ;
INSERT INTO TOURPLACE VALUES ( 59 , 'HAMPE' , 'ALL SEASON' ) ;


--

INSERT INTO TOURPLACE_SITE VALUES ( 1 , 'NANDIHILLS' , 'HILLSTATION') ;
INSERT INTO TOURPLACE_SITE VALUES ( 2 , 'NANDIHILLS' , 'HILLSTATION') ;
INSERT INTO TOURPLACE_SITE VALUES ( 3 , 'NANDIHILLS' , 'HILLSTATION') ;
INSERT INTO TOURPLACE_SITE VALUES ( 4 , 'NANDIHILLS' , 'HILLSTATION') ;

INSERT INTO TOURPLACE_SITE VALUES ( 5 , 'NANDIHILLS' , 'HILLSTATION') ;
INSERT INTO TOURPLACE_SITE VALUES ( 6 , 'NANDIHILLS' , 'HILLSTATION') ;
INSERT INTO TOURPLACE_SITE VALUES ( 7 , 'NANDIHILLS' , 'HILLSTATION') ;
INSERT INTO TOURPLACE_SITE VALUES ( 8 , 'NANDIHILLS' , 'HILLSTATION') ;


INSERT INTO TOURPLACE_SITE VALUES ( 9 , 'NANDIHILLS' , 'HILLSTATION') ;
INSERT INTO TOURPLACE_SITE VALUES ( 10 , 'NANDIHILLS' , 'HILLSTATION') ;
INSERT INTO TOURPLACE_SITE VALUES ( 11 , 'NANDIHILLS' , 'HILLSTATION') ;
INSERT INTO TOURPLACE_SITE VALUES ( 12 , 'NANDIHILLS' , 'HILLSTATION') ;


INSERT INTO TOURPLACE_SITE VALUES ( 44 , 'ULLALA' , 'BEACH' ) ;
INSERT INTO TOURPLACE_SITE VALUES ( 44 , 'PANAMBUR' , 'BEACH' ) ;
INSERT INTO TOURPLACE_SITE VALUES ( 44 , 'St. Mary Iland' , 'BEACH' ) ;
INSERT INTO TOURPLACE_SITE VALUES ( 44 , 'KRISHNA' , 'TEMPLE' ) ;


--

INSERT INTO PACKAGES VALUES ( 1 , 'INDO-NEPAL' ,'INTERNATIONAL',8000,2000 , 8 ) ;
INSERT INTO PACKAGES VALUES ( 2 , 'KASHI-NEPAL-GAYA','INTERNATIONAL',10000 , 2000 , 8 ) ;
INSERT INTO PACKAGES VALUES ( 3 , 'NEPAL-AYODYA-PURI','INTERNATIONAL',16000 , 2000 , 12 ) ;


INSERT INTO PACKAGES VALUES ( 4 , 'NORTH INDIA' ,'NORTHEN PACKAGES',12000,8800 , 22 ) ;
INSERT INTO PACKAGES VALUES ( 5 , 'SIMLA-MANALI-AMRITHSAR','NORTHEN PACKAGE',10000 , 8500 , 15 ) ;
INSERT INTO PACKAGES VALUES ( 6 , 'RAJASTHAN SPEIAL','NORTHEN PACKAGE',9995 , 9800 , 16 ) ;


INSERT INTO PACKAGES VALUES ( 7 , 'SOUTH INDIA' ,'SOUTHERN PACKAGE',4500,3600 , 10 ) ;
INSERT INTO PACKAGES VALUES ( 8 , 'GOA-MUBAI','SOUTHERN PACKAGE',4450 , 2250 , 8 ) ;
INSERT INTO PACKAGES VALUES ( 9 , 'THIRUPATHI-HYDRABAD','SOUTHERN PACKAGE',3250 , 3000 , 7 ) ;



-- 

INSERT INTO PACKAGE_PLACE VALUES ( 7,1 ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 7,2 ) ;
INSERT INTO PACKAGE_PLACE VALUES (7, 3  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 7,4  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 7,5  ) ;

INSERT INTO PACKAGE_PLACE VALUES ( 1,6  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 1,7  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 1,8  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 1,9  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 1,10  ) ;

INSERT INTO PACKAGE_PLACE VALUES ( 3,11  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 3,12  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 3,13  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 3,14  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 3,15  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 3,16 ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 3,17 ) ;

INSERT INTO PACKAGE_PLACE VALUES ( 2,18 ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 2,19  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 2,20 ) ;

INSERT INTO PACKAGE_PLACE VALUES ( 3,21  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 3,22) ;
INSERT INTO PACKAGE_PLACE VALUES ( 3,23  ) ;

INSERT INTO PACKAGE_PLACE VALUES ( 4,24 ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 4,25  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 4,26  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 4,27  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 4,28  ) ;

INSERT INTO PACKAGE_PLACE VALUES ( 5,29  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 5,30 ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 5,31  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 5,32  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 5,33  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 5,34  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 5,35  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 5,36  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 5,37 ) ;

INSERT INTO PACKAGE_PLACE VALUES ( 6,40 ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 6,41 ) ;

INSERT INTO PACKAGE_PLACE VALUES ( 7,42) ;
INSERT INTO PACKAGE_PLACE VALUES ( 7,43  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 7,44 ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 7,45) ;
INSERT INTO PACKAGE_PLACE VALUES ( 7,46  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 7,47 ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 7,48 ) ;

INSERT INTO PACKAGE_PLACE VALUES ( 8,49  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 8,50 ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 8,51  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 8,52 ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 8,53 ) ;

INSERT INTO PACKAGE_PLACE VALUES ( 9,54 ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 9,55 ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 9,56  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 9,57  ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 9,58 ) ;
INSERT INTO PACKAGE_PLACE VALUES ( 9,59  ) ;


--


