drop table BOOKING;
drop table RECEIPT;
drop table BILLMASTER;
drop table TOUR;
drop table PACKAGE_PLACE;
drop table PACKAGES;
drop table TOURPLACE_SITE ;
drop table TOURPLACE;
drop table BUS;
drop table BRANCH;

CREATE TABLE BRANCH(
	PNAME VARCHAR2(10) CONSTRAINT FORBRANCHNAME PRIMARY KEY,
	ADDRES1 VARCHAR2(30),
	TELE NUMBER(10)
);

CREATE TABLE BUS(
	BUSNO VARCHAR2(20) CONSTRAINT PMKBUSNO PRIMARY KEY,
	BTYPE VARCHAR2(20) CONSTRAINT NONBTYPE NOT NULL,
	STYPE VARCHAR2(20),
	NSEAT NUMBER(3)
);

CREATE TABLE PACKAGES(
	PKID NUMBER(2) CONSTRAINT PMKKID PRIMARY KEY,
	TNAME VARCHAR2(10) CONSTRAINT PACKNAME NOT NULL,
	FARE NUMBER(8) CONSTRAINT RUPEES NOT NULL,
	TKM NUMBER(8),
	DURATION NUMBER(3)
);

CREATE TABLE TOURPLACE (
	PLID NUMBER(4) CONSTRAINT PMKPLID PRIMARY KEY,
	PLACE VARCHAR2(30),
	SEASON VARCHAR2(50)
);

create table package_place (
	pkid number(2) constraint refpkid references packages,
	plid number(4) constraint refplid references tourplace,
	CONSTRAINT COMPMK PRIMARY KEY (PKID,PLID) ) ;

CREATE TABLE TOURPLACE_SITE (
	PLID NUMBER(4) CONSTRAINT REF_TS_PLID REFERENCES TOURPLACE,
	SITE VARCHAR2(50) CONSTRAINT NONSITE NOT NULL,
	SITETYPE VARCHAR2(20) CONSTRAINT NONSITETYPE NOT NULL
) ;
	

CREATE TABLE TOUR (
	TID VARCHAR2(10) PRIMARY KEY,
	PKID NUMBER(2) CONSTRAINT FORTOURPKID REFERENCES PACKAGES,	
	DODEPARTURE DATE,
	DOARRIVAL DATE,
	BUSNO VARCHAR2(20) CONSTRAINT FORTOURBUSNO REFERENCES BUS,
	TOTALSEATS NUMBER(3) ,
	FARE NUMBER(8)
);

CREATE TABLE BILLMASTER(
        BILLNUM number(5) CONSTRAINT FORBILLNO PRIMARY KEY,
	PNAME VARCHAR2(10) CONSTRAINT BILLNAME REFERENCES BRANCH,
        TID VARCHAR2(10) CONSTRAINT FORBILLTID REFERENCES TOUR,
	DOB DATE,
	TOTAL number(8,2),
	BALANCES number(8,2),
	ADDRESS1 varchar2(30),
	ADDRESS2 varchar2(30),
	TELEPHONE number(8)		
);

create table BOOKING(
	BILLNUM NUMBER(5) CONSTRAINT BOOKINGBILL REFERENCES BILLMASTER,
	SLNO NUMBER(5),
	NAME VARCHAR2(20),
	SEX VARCHAR2(5) CONSTRAINT BOOKSEX check(SEX IN('f','m','F','M')),
	Age NUMBER(5),
	SEAT NUMBER(5),
	RELATION VARCHAR2(9)
);

CREATE TABLE RECEIPT (
	BILLNUM NUMBER(5) CONSTRAINT PMKRECEIPTBILLNO REFERENCES BILLMASTER,
	DOR DATE,
	OLDBALANCE NUMBER(8,2),
	AMOUNT NUMBER(8,2),
	NEWBALANCE NUMBER(8,2),
	RECNO NUMBER(8) CONSTRAINT PMKRECEIPTRECNO PRIMARY KEY
);