create or replace view  as(
select 
LID
FROM  PACKAGES PK, TOURPLACE TP, TOURPLACE_SITE TS,PACKAGE_PLACE PP
WHERE (PK.PKID = PP.PKID) AND (PP.PLID = TP.PLID) AND (TP.PLID = TS.PLID)) ;

CREATE OR REPLACE VIEW PACK_TOUR_PLACE AS (
SELECT P.PKID,PK.TNAME,PK.FARE,PK.TKM,PK.DURATION,P.PLID,T.PLACE,T.SEASON
FROM PACKAGE_PLACE P,PACKAGES PK,TOURPLACE T
WHERE P.PKID=PK.PKID
AND P.PLID=T.PLID) ;

create oR REPLACE VIEW TOUR_PACK AS (
select t.*,p.tname,p.pkname,p.tkm,p.duration
from tour t,packages p
where t.pkid=p.pkid) ;

CREATE OR REPLACE VIEW TOUR_PLACE_SITE AS (
SELECT T.PLID,T.PLACE,
TS.SITE,TS.SITETYPE
FROM TOURPLACE T,TOURPLACE_SITE TS) ;

CREATE OR REPLACE VIEW BMBALANCE AS (
SELECT BILLMASTER.*,TO_CHAR(BILLMASTER.DOB,'MON-YYYY') MONTHBALANCE
FROM BILLMASTER
WHERE BALANCES<>0 OR BALANCES IS not NULL ) ;

CREATE OR REPLACE VIEW PACK_PLACE AS (
SELECT P.PKID, PL.PLID , PL.PLACE , PL.SEASON
FROM PACKAGES P, TOURPLACE PL , PACKAGE_PLACE PP
WHERE P.PKID=PP.PKID
AND PP.PLID = PL.PLID ) ;